controller_manager:
  ros__parameters:
    update_rate: 100 # Hz
    use_sim_time: true

    fishbot_joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    fishbot_effort_controller:
      type: effort_controllers/JointGroupEffortController

fishbot_effort_controller:
  ros__parameters:
    joints:
      - left_wheel_joint
      - right_wheel_joint
    
    command_interfaces:
      - effort
    
    state_interfaces:
      - position
      - velocity
      - effort